{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Orders\",\"Details\",\"All DAX\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.135.7627.0 (24.08)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "f3e4016b-d54b-4774-a49c-48fcd3928323",
        "fromColumn": "Date",
        "fromTable": "Calendar",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_3a9eb2f7-4465-4d34-b212-f71313fbcdb7"
      },
      {
        "name": "1299ce5c-1e70-741b-ee6d-9e3d6d8b0fa4",
        "fromColumn": "Order Date",
        "fromTable": "Orders",
        "toColumn": "Date",
        "toTable": "Calendar"
      }
    ],
    "sourceQueryCulture": "en-AE",
    "tables": [
      {
        "name": "Orders",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Order ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a1aeaf6c-59f5-4162-8d17-497c81047b16",
            "sourceColumn": "Order ID",
            "summarizeBy": "none"
          },
          {
            "name": "Order Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "34c3fd44-f1e7-4548-b146-bd25c390d705",
            "sourceColumn": "Order Date",
            "summarizeBy": "none"
          },
          {
            "name": "CustomerName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "154efff8-009e-45c8-a682-c8cf79454184",
            "sourceColumn": "CustomerName",
            "summarizeBy": "none"
          },
          {
            "name": "State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d4de365a-d43c-4420-8b4b-8827ba1422f7",
            "sourceColumn": "State",
            "summarizeBy": "none"
          },
          {
            "name": "City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8f3e1770-d711-44a6-ae7b-329870915d21",
            "sourceColumn": "City",
            "summarizeBy": "none"
          },
          {
            "name": "Details.Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "97259cb0-453e-455a-a75b-a290f5bb7ce9",
            "sourceColumn": "Details.Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Details.Profit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c7c47172-16e2-406f-bf31-d13245d973b9",
            "sourceColumn": "Details.Profit",
            "summarizeBy": "sum"
          },
          {
            "name": "Details.Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5416b64a-b09f-4f74-a6ca-7211a5aa0c54",
            "sourceColumn": "Details.Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Details.Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1995bc12-13de-48d0-b96c-9293f44e1ee2",
            "sourceColumn": "Details.Category",
            "summarizeBy": "none"
          },
          {
            "name": "Details.Sub-Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b82b6321-188a-4f34-a0a3-f2824372dd78",
            "sourceColumn": "Details.Sub-Category",
            "summarizeBy": "none"
          },
          {
            "name": "Details.PaymentMode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c6d9ec43-9146-4837-8ac3-10254905677b",
            "sourceColumn": "Details.PaymentMode",
            "summarizeBy": "none"
          },
          {
            "name": "P/L",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "IF(Orders[Details.Profit]>0,\"Profit\",\"Loss\")",
            "isDataTypeInferred": true,
            "lineageTag": "1c21848a-a4e3-49fc-b9c0-cd45160a30b3",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "780c519d-c882-482d-b515-2349d203ec98",
        "partitions": [
          {
            "name": "Orders",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\mohammed.nayaz\\Downloads\\Orders.csv\"),[Delimiter=\",\", Columns=5, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Order ID\", type text}, {\"Order Date\", type date}, {\"CustomerName\", type text}, {\"State\", type text}, {\"City\", type text}}),",
                "    #\"Merged Queries\" = Table.NestedJoin(#\"Changed Type\", {\"Order ID\"}, Details, {\"Order ID\"}, \"Details\", JoinKind.LeftOuter),",
                "    #\"Expanded Details\" = Table.ExpandTableColumn(#\"Merged Queries\", \"Details\", {\"Amount\", \"Profit\", \"Quantity\", \"Category\", \"Sub-Category\", \"PaymentMode\"}, {\"Details.Amount\", \"Details.Profit\", \"Details.Quantity\", \"Details.Category\", \"Details.Sub-Category\", \"Details.PaymentMode\"})",
                "in",
                "    #\"Expanded Details\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_bf2f2ba8-3fbb-4e38-8ba0-ba9b90e76e88",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "a5f15933-4a94-4c8a-9d52-15f3a6953afe",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "47a69074-76fe-48d4-bf3a-85a23b037065",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "cd818373-4151-497d-a9d6-faa18a1c58ef",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "c5c29560-a3fc-4c0d-9438-2ae35ad93a6a",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c8a71961-7dfd-4172-919b-683549cbfe56",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "c091eac1-8892-4474-b81d-2710eadad724",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "4543d830-b193-4e4e-b07a-bb0b42913b75",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "115a6922-98a4-479f-b792-cfb800bb80b4",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "99f6f701-5766-4ff7-ad32-512656a95719",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "890d6051-9084-48e4-922c-8c8d99f8517d",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "6202f706-2ef2-4b18-9c29-574ec5939344",
                "ordinal": 3
              }
            ],
            "lineageTag": "240c0eb9-1747-4c3d-a367-4cd7b798cf93"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "405aff64-bb43-48c9-a3dd-e6c0083b6960",
        "partitions": [
          {
            "name": "DateTableTemplate_bf2f2ba8-3fbb-4e38-8ba0-ba9b90e76e88",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Details",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Order ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7e09341a-1678-4c28-871c-be632676b14a",
            "sourceColumn": "Order ID",
            "summarizeBy": "none"
          },
          {
            "name": "Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "28561eb0-4796-44b6-8462-ce4ec1cbfd55",
            "sourceColumn": "Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Profit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8fc60e40-55b1-49d1-9971-ae0a54d65987",
            "sourceColumn": "Profit",
            "summarizeBy": "sum"
          },
          {
            "name": "Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "83cb9658-9c1c-4040-8388-8be7f17c60fe",
            "sourceColumn": "Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a542f29d-8178-46f1-90aa-73a2e5bc44ef",
            "sourceColumn": "Category",
            "summarizeBy": "none"
          },
          {
            "name": "Sub-Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "14ef76a9-0545-410c-bbfb-1f06395fba11",
            "sourceColumn": "Sub-Category",
            "summarizeBy": "none"
          },
          {
            "name": "PaymentMode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a185a2b3-8f39-494c-b3bb-894c4e4b8b2a",
            "sourceColumn": "PaymentMode",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "517b631a-4572-4bff-8882-172bd3b28073",
        "partitions": [
          {
            "name": "Details",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\mohammed.nayaz\\Downloads\\Details.csv\"),[Delimiter=\",\", Columns=7, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Order ID\", type text}, {\"Amount\", Int64.Type}, {\"Profit\", Int64.Type}, {\"Quantity\", Int64.Type}, {\"Category\", type text}, {\"Sub-Category\", type text}, {\"PaymentMode\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "All DAX",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Column1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7bcbc703-9da0-4a5d-9129-a9a01bd06cdd",
            "sourceColumn": "Column1",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "eb10ea72-6fd1-4fc1-9990-ab7cdb4c5f54",
        "measures": [
          {
            "name": "Order",
            "expression": "DISTINCTCOUNT(Orders[Order ID])",
            "formatString": "0",
            "lineageTag": "2334d836-8d50-4f5b-9db3-45ede13f784f"
          },
          {
            "name": "QTY",
            "expression": "SUM(Details[Quantity])",
            "formatString": "0",
            "lineageTag": "2b53bac1-27f9-46b4-9b44-a97c3332a624"
          },
          {
            "name": "Sales",
            "expression": "SUM(Orders[Details.Amount])",
            "formatString": "0",
            "lineageTag": "177168de-d2cc-430b-8655-af8f00a03536"
          },
          {
            "name": "Revenue",
            "expression": "SUM(Orders[Details.Profit])",
            "formatString": "0",
            "lineageTag": "b6b90512-1197-46a0-bcf3-d43df900411c"
          },
          {
            "name": "Customers",
            "expression": "DISTINCTCOUNT(Orders[CustomerName])",
            "formatString": "0",
            "lineageTag": "a0906502-7c99-4e2b-9cec-09d29e3bdb7c"
          }
        ],
        "partitions": [
          {
            "name": "All DAX",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Calendar",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "0a3a04356232471c8eef71bf20b81fd0"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "dd41c2c1-1046-47fb-95c1-66d12805af2c",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_3a9eb2f7-4465-4d34-b212-f71313fbcdb7"
                },
                "isDefault": true,
                "relationship": "f3e4016b-d54b-4774-a49c-48fcd3928323"
              }
            ]
          },
          {
            "name": "Q",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "QUARTER('Calendar'[Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "ef73af16-1216-400c-8fa9-bfc7f4432685",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Q_Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "\"Q -\"&'Calendar'[Q]",
            "isDataTypeInferred": true,
            "lineageTag": "bb0b4efb-23ce-410d-a690-b53db8768a5e",
            "sortByColumn": "Q",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT('Calendar'[Date],\"MMMM\")",
            "isDataTypeInferred": true,
            "lineageTag": "93efcb2c-f696-41a1-b3e2-2ab441fcbd67",
            "sortByColumn": "Calendar Month",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Calendar Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "MONTH('Calendar'[Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "98374401-3a4b-4111-a5a2-311f01bef416",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "da99f5c3-da47-45ab-a1d7-f42d4e149581",
        "partitions": [
          {
            "name": "Calendar",
            "mode": "import",
            "source": {
              "expression": "CALENDAR(MIN(Orders[Order Date]),MAX(Orders[Order Date]))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_3a9eb2f7-4465-4d34-b212-f71313fbcdb7",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "561d01f7-0bc0-42f5-acbb-0e66cc7d11ae",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "0bfa7e57-98de-4c1e-891d-eb3aa0807272",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a57cb704-5455-455b-a61a-ef6a4dde94dc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "3cc7320b-d156-472a-b420-cd32e5100bf1",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "7d90800b-24b9-4310-a417-baeb353ed0b1",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "39e800d4-610e-45ed-a927-dafc920344b2",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f17485fe-842a-48c5-8d06-ca5a87fabf57",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "fd953e78-123f-4965-beb3-c5bdea41330b",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "182dc4d5-4bef-4a09-8320-72e41ecf183d",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "c855f5b6-2935-49e4-8069-ac147856d2c6",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "4ac4b46a-975b-46e6-a037-489a8271e869",
                "ordinal": 3
              }
            ],
            "lineageTag": "06ec5120-ad51-47b7-8d4b-619934e0a422"
          }
        ],
        "isHidden": true,
        "lineageTag": "ee2244c9-92fc-41e0-9f80-0e573530ecaf",
        "partitions": [
          {
            "name": "LocalDateTable_3a9eb2f7-4465-4d34-b212-f71313fbcdb7",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Calendar'[Date])), 1, 1), Date(Year(MAX('Calendar'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}